---
version: "3.8"
services:
  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack
    env_file:
      -.env
    volumes:
      - ./config/bookstack:/config
    ports:
      - 6875:80
    restart: unless-stopped
    depends_on:
      - bookstack_db
  bookstack_db:
    image: lscr.io/linuxserver/mariadb
    container_name: bookstack_db
    env_file:
      - .env
    volumes:
      - ./config/mariadb:/config
    restart: unless-stopped